import string
import re

ALLOWED_SYMBOLS = string.ascii_letters + string.digits
CUSTOM_LINK_PATTERN = re.compile(f"^[{re.escape(ALLOWED_SYMBOLS)}]*$")
MAX_ORIGINAL_LINK_LENGTH = 2048
MAX_CUSTOM_LINK_LENGTH = 16
MAX_AUTOGENERATE_CUSTOM_LINK_LENGTH = 6
MAX_ITERATIONS = 10
